---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: communication
components:
  - ../../components/common
resources:
  #- ./matrix-synapse/ks.yaml
