---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm
components:
  - ../../components/namespace
resources:
  - ./open-webui/ks.yaml
  - ./searxng/ks.yaml
  - ./ollama/ks.yaml
replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: Kustomization
          group: kustomize.toolkit.fluxcd.io
        fieldPaths:
          - spec.targetNamespace
        options:
          create: true
