---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm
components:
  - ../../components/common
resources:
  # Flux-Kustomizations
  - ./open-webui/ks.yaml
  - ./searxng/ks.yaml