---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: localai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: localai-secret
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: localai
        property: HF_TOKEN
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: localai
        property: OPENAI_API_KEY
