---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: r2
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: s3://cloudnative-pg/
    endpointURL: http://aionios.internal:30157
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cloudnative-pg-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: bzip2
      maxParallel: 8
  retentionPolicy: 30d
