---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: slskd-secret
    template:
      engineVersion: v2
      data:
        SLSKD_SLSK_USERNAME: "{{ .SLSK_USERNAME }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSK_PASSWORD }}"
  dataFrom:
    - extract:
        key: slskd
