---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/apps/v1/daemonset.json
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-xpumanager
  labels:
    app.kubernetes.io/name: intel-xpumanager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: intel-xpumanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: intel-xpumanager
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: xpumd
          image: intel/xpumanager:v1.2.27@sha256:7c2123abfdf87ba97fce3865e0db86a8728a8fefdebe96961ab066b2aabcbc86
          imagePullPolicy: IfNotPresent
          command:
            - /usr/bin/xpumd
          env:
            - name: SPDLOG_LEVEL
              value: info
            - name: XPUM_REST_NO_TLS
              value: "1"
            - name: XPUM_EXPORTER_NO_AUTH
              value: "1"
            - name: XPUM_EXPORTER_ONLY
              value: "1"
          resources:
            limits:
              gpu.intel.com/i915_monitoring: 1
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 0
            capabilities:
              drop: ["ALL"]
              add: ["SYS_ADMIN"]
          volumeMounts:
            - name: kubeletpodres
              mountPath: /var/lib/kubelet/pod-resources
            - name: sockdir
              mountPath: /tmp
        - name: python-exporter
          image: intel/xpumanager:v1.2.27@sha256:7c2123abfdf87ba97fce3865e0db86a8728a8fefdebe96961ab066b2aabcbc86
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 0
            capabilities:
              drop: ["ALL"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: XPUM_EXPORTER_NO_AUTH
              value: "1"
            - name: XPUM_EXPORTER_ONLY
              value: "1"
          workingDir: /usr/lib/xpum/rest
          command:
            - gunicorn
            - --bind
            - 0.0.0.0:29999
            - --worker-connections
            - "64"
            - --worker-class
            - gthread
            - --workers
            - "1"
            - --threads
            - "4"
            - xpum_rest_main:main()
          ports:
            - containerPort: 29999
              name: metrics
              protocol: TCP
          startupProbe:
            httpGet:
              path: /metrics
              port: metrics
            failureThreshold: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healtz
              port: metrics
            initialDelaySeconds: 60
            periodSeconds: 10
          volumeMounts:
            - name: sockdir
              mountPath: /tmp
            - name: devdri
              mountPath: /dev/dri
              readOnly: true
      volumes:
        - name: kubeletpodres
          hostPath:
            path: /var/lib/kubelet/pod-resources
            type: ""
        - name: sockdir
          emptyDir:
            medium: Memory
        - name: devdri
          hostPath:
            path: /dev/dri
