---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: intel-xpumanager
  labels:
    app.kubernetes.io/name: intel-xpumanager
spec:
  ports:
    - name: metrics
      port: 29999
      protocol: TCP
  selector:
    app.kubernetes.io/name: intel-xpumanager
  sessionAffinity: None
