---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: home-assistant
spec:
  image: ghcr.io/homeassistant-ai/ha-mcp:7.14.2@sha256:7917b2d385e16e43f45f92fc72a757e5c0aec8d88b3cd69fe64f3b5106cbfe36
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 8086
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    - name: HOMEASSISTANT_URL
      value: http://home-assistant.services.svc.cluster.local:8123
  secrets:
    - name: toolhive-home-assistant
      key: HOMEASSISTANT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          command:
            - ha-mcp-web
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
  groupRef:
    name: mcp-tools
