apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
  namespace: security
  labels:
    type: oracle
type: oracle
stringData:
  privateKey: ENC[AES256_GCM,data:c6eXVrltxl+Ve6SyzLQtgkS49SpQwRnF/HbRTWHpFeU2xqq6Y7eXwWMdQWwZn3cg8K8gNfVRxCGBL4kjNtAFuKM8SacNTKcGHRZ6V8YaVsKv3gCQCtISAV0eGTCyCLhYA2j0W+bXwqNVMgzt6vJZVYpgaHC7d2KTzVKjKDC+HyhMMEyMIepfejFPn8ii1kL+lwJba5cCKsyJVhH0OPTU5VOE74rGNzHkKeHFoOSmKHu3qB7FzQFUbnUsDEsV4rQKvC+Urxivc/wlW4oLDkguF8Fe2Wq/kHrn5+sm4xemGz5zLYUSXJdkCcSuz9V3+G6o8WMVCiHt8dCGErRmHUKlHwc6wBWFrT9AG08vrbFZrMSaC4ZgULe8FlsY+xnbK1vxPTb3W+JaAaqVJQXA1yxmTqNmK9PFU6LCh5X/dZ2zH859pmI41TYuO4N6aMbZAIYvzCHdlH1BcjFYz9oEskXdBOcyR7TY2quPRgIGf0G2krUOsvtDirquNOVCUTmn5gUoBgo4FzKIz9cH9ldFCvXhKS4Vd6Ms9qi87gAjC+y+4wSEpIhifusqtbFqaMyUMuLd4FI/9CVxi3uJA8Ibv4ljkcZuOfTEceySBZo4No8umZyRKHJDBN1HS+BEzESmVvLo5rH7XQ5ZVVyopX5FmLZkD5gScm4hpuExbhiCUnF8yacZiK/H3pISbassqCkkp5M4uz74YuMgyht/LfRtxRykV0loTh4BU8BQ1vhbhc6fj4y9J2GGxjuzY8d1G5YhyEDQOK2Y00N18xb9OgyxSFVTPmGKYuvp7DV6unUCzyx9VEUD7P9+jF/CFzV2SD0+kuEWqLY5KjrrI8YfqssEcLS3Mxli4+bRP6bBKOQvlUwNOpOeJyVt1ir8oY/hU4SJrz7QVtTzENOZP9HA6o4HQCV6VZYB+DIchzyiqzhvHU4smi87o1xutw84WQ1bqMXtfk54QqvwcFqjYrFELq+SLFabNRgUG/0NXOIzAEsRhTOdVsY6Hkk4MYU3DWaJNlVZYssJwE5oREkiGP1PHexkdqRndNBnonZb6q7Ip/CPAObm2T59zfKL9zG3hqS1gyzC93URcOIWvY26NXoBg/Lo8965+fDYqk4fib1eA7hiBgXzvOaw88v0r2qGJ0iH1jk4ntJ4CreTvZ/uI+4l60eyjR0mB9n9Of0D9KI+Xw+ySdaVELp/MOzrY1FruBzbwq9oQy5EwTinfAeQrCnoFtyqXLgTUR3gQbPXYSeGRGOpOhw8m6ogU/rSs51NyUsotmu2YuJr98Hoo/804WmiIwlopzXb0f/f8II8BXVfFUfMlDeDr4XbtqyFlfRIIs0B/BtaVNjxZUBNi/qo8+uZ04EZeIuUHNlo9agAnaC19d28LvsJPFEvFftm+tMREBgMTbUcvqPSrqpSJZAOtRqcroneHP7/3/+smVHI1qVD+EdZmyjxh6cATV3YXVN3Gni6ohhJUXdlWvmzAdR2ZDyTSbnaC21BjpzmfvGbMlkyM746935IWsGS2dJ195tO7ZjCaXrXr5I1s0OBmhbDv/4vSEOkjD+1tM6LycK8wVlR95h6Vlgwe9ZJNfL/sKuTb/rBt8nidWYKhHNnSFszP8iZvv72zPnfMNkXqwpMTpaGsJcL2inL1g6KiDTjSv3NWiMi4zCgTFmUjJ+jgsclmeL9v1IDAkxTAddmN3MyRWmLW1M+waPgameOYQG3/pItlt9lcyMWHAk3nfnAGpiRxfzBmXDDe6HabT+35Q5HITI+5Z7PVUMZyvZNTWse4NRj142jDeLU1A2xuyVhNk5+50qnXDhfm2SAcQpumA+HAfrCrJ4dRLCfldtcoVdxgtpEtxZBsEZpysRBX+bPmAlOUnVQ5rfMKbbPU4Uu9NoF748i/FWSVFxaAtCyY5TGY9NW2xtfS1vNu4OpjLjXmOrTRiS9WNQPL8phRU835ppsOm8J5hoM7z3BMRK6XC78Kpsvj+KsV49scND8nIAfi5Fl5LWnGho7UysPOzAhjq/+3kwiqrLQ4oVABzfkWnn/xEb/SDZKeNzXz10ubYgTFPzfGVJj0Zf44Di5WizIzEDSGAntEHkMEOPvj4Ffw50iy7kil/mwSyGOYhzpZue1Yhp4iJHvtZOkagXEU3bjJ/025QUIdnw7UKguotxsinh8aBnrd8ZGVwXM0UkwP3hKM4Jv8McadR/zTUZaCSN9k0MHqn/HbZBpkuLkFaHoAFjLzSTM18P5z9lFGx2hFI+Br9yUgFofx0/bbQFem3fqGLbr4w3i,iv:iE+h5eMWQU7yIijkUEFEAGX8JgfjMknmYRztcmqzwag=,tag:vnmRTWNzGW2TpKkOb0KsDA==,type:str]
  fingerprint: ENC[AES256_GCM,data:4rR6JHj4niM8I2gzYxklaAlf3vZk7qslYkzg5kRaCioYodd0us1jY3lSX86wyx4=,iv:nCTusuz2t/6kg8wM3mxCJqBU9GVapjsIgOMoUbbMwaQ=,tag:lBrgnWtscaUXSsfa5Kn6Zg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1t9dt4x2h77mduu8xm0ru3hyr5vy8afrw9474ukfv7ws5hae5kc8styg36m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcHJZTnBSVG5Ocm9COStR
        NmY2enNRalZzeHZmUmFBRnpSSHczYTlpOVM0CmVHelBRWXdoSERWU1NMaFI0Y2hL
        MWR6VVBaZHM0aVo2aE9TNXFtbWZla0kKLS0tIDRhRm5TLzNQcGhXZHhPbnRJVU1j
        Q0dQQlZScmhMaFVjYVRVaG1vTzkzUVEK7JX98wP8cDXHIMIE5t4suYGTnlmQJ2WI
        eRsusem9ww7fYAKpCc9MKOFukcuAYMCsZcFDKMXQ1Py7j5Qidd3fTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-14T13:18:52Z"
  mac: ENC[AES256_GCM,data:HKICw+AJ5CYYV+lMso5mHW/uenlAXCb8UqahudmSQX3LYWJveSYB7/o2S/ORVM0RUrFo/fsM0+opChNgGP5jd7MUd91j2VSCEqC/37BbnMVH1nWEyq2PRZhpPpJmFRjAWf1I+oksl1zL5gRSYXeiKJHOK4DSqJIS8e5p9iEJt9Y=,iv:WgLL29VKYzplyPhmNf7XfEJw9truZwFu/fLh/UTYV4I=,tag:umqoONAZaueL83zQhH58BA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
