---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kromgo
spec:
  components:
    - ../../../../components/gatus/external-two
  interval: 1h
  path: ./kubernetes/apps/observability/kromgo/app
  postBuild:
    substitute:
      APP: kromgo
      GATUS_PATH: /talos_version
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
