[env]
#_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/kubernetes/bootstrap/talos/clusterconfig/talosconfig"
# Included file paths
_.file = [
  "{{config_root}}/onepassword.env",
]

#[tasks.deps]
#description = "Install dependencies"
#run = "uv pip install -r requirements.txt"

[tools]
# Template tools
#python = "3.13"
#uv = "0.6.14"
# Operations tools
#"aqua:budimanjojo/talhelper" = "3.0.21"
#"aqua:cloudflare/cloudflared" = "2025.4.0"
#"aqua:FiloSottile/age" = ["1.2.1"]
#"aqua:fluxcd/flux2" = "2.5.1"
#"aqua:getsops/sops" = "3.10.2"
#"aqua:go-task/task" = "3.42.1"
#"aqua:helm/helm" = "3.17.3"
#"aqua:helmfile/helmfile" = "0.171.0"
#"aqua:jqlang/jq" = ["1.7.1"]
#"aqua:kubernetes-sigs/kustomize" = ["5.6.0"]
#"aqua:kubernetes/kubectl" = "1.32.3"
#"aqua:mikefarah/yq" = ["4.45.1"]
#"aqua:siderolabs/talos" = "1.9.5"
#"aqua:yannh/kubeconform" = ["0.6.7"]
#"aqua:robscott/kube-capacity" = ["0.8.0"]
