apiVersion: v1
kind: Pod
metadata:
  name: multi-net-pod
  namespace: network
  annotations:
    k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.0.40.157/24"],
                "mac": "48:c3:71:7c:c5:27"
              }]
spec:
  nodeSelector:
    kubernetes.io/hostname: pneuma
  containers:
  - name: app
    image: nginx
    command: ["/bin/sh", "-c", "sleep infinity"]
    ports:
      - containerPort: 80
