apiVersion: v1
kind: Pod
metadata:
  name: multi-net-pod
  namespace: network
  annotations:
    k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-mgt",
                "namespace": "network",
                "ips": ["192.168.0.156/24"]
              }]
spec:
  containers:
  - name: app
    image: nginx
    command: ["/bin/sh", "-c", "sleep infinity"]
    ports:
      - containerPort: 80
