apiVersion: v1
kind: Pod
metadata:
  name: multi-net-pod
  namespace: network
  annotations:
    k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.0.40.153/24"],
                "mac": "92:cf:d7:05:70:85"
              }]
spec:
  containers:
  - name: app
    image: nginx
    command: ["/bin/sh", "-c", "sleep infinity"]
    ports:
      - containerPort: 80
