# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CYWmC7ZNeK/0jlh890u0wc9LjRJ7ByUvJ68qGpNxLik=,iv:rQCdpgORBLtS7pcV/g9LUtPe7GD5h/m+kLy+4wmdkCA=,tag:p5rTj99WSAVa/xFWzIhkmA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1t9dt4x2h77mduu8xm0ru3hyr5vy8afrw9474ukfv7ws5hae5kc8styg36m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZE40L1Exd0oxVTVibWpl
        RDJmZ2FiMU5sZFdodk9RVVowQzNiZktlOEg4CndTa0VKMEdMZ1JvS3l2cjFHSGhP
        bjhMcUZpUk5DQ1c1MnlKeUlwUlk1RW8KLS0tIHUyVlBkaTN4ZjVjZkU3VEE5SldZ
        Q1hGZHFVVzZSQjRGV2dmaXFjV0ZPTTAKdlZyb77PGNzFM9uqMPQQNiCQJM6lA2M4
        pJy6q6ZHGdS8jWjxp7lhK9ii+D6yekkI+ivPQljoz+DfwQP6dWsqYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-14T12:33:52Z"
  mac: ENC[AES256_GCM,data:0k6VC8atxHAfSqsCK75OnwQGPhdqiIIb+Rgs/lY957HavicgLEFe7cwJZ4eAtBLjBp6k31jwR/9AjpjLccx2g/HolTznpeFrTzMb/CO9fQmRXH47HBU1FGjiAvW1J8mF5snCSM3OGAkywq9NbDh0p58LK2Ya5azNCwyt+4AA1GM=,iv:fjpZGyyqeZNeAIKq7IfvhP0cc9qh/I1DTWJ7iAfBVsc=,tag:cXiiwMb8dfFxPR46ckUOAg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
