---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app stirling-pdf
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      stirling-pdf:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stirling-tools/s-pdf
              tag: 1.2.0@sha256:4b549915161efdf8a7c43bf0ad3b5d5d39f0cb0be58b7dcce1d1b62fbe8ed818
            env:
              TZ: Europe/London
              DOCKER_ENABLE_SECURITY: false
              SYSTEM_ENABLEANALYTICS: false
              INSTALL_BOOK_AND_ADVANCED_HTML_OPS: true
            probes:
              liveness: &probe
                enabled: true
                type: HTTP
                path: /api/v1/info/status
              readiness: *probe
              startup:
                <<: *probe
                spec:
                  failureThreshold: 90
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 1000Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        annotations:
          teleport.dev/name: *app
        labels:
          teleport: enabled
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames: ["pdf.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /configs
      tmpfs:
        type: emptyDir
        advancedMounts:
          stirling-pdf:
            app:
              - path: /logs
                subPath: logs
              - path: /pipeline
                subPath: pipeline
              - path: /usr/share/tessdata
                subPath: tessdata
              - path: /tmp
                subPath: tmp
