---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app stirling-pdf
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stirling-tools/s-pdf
              tag: 0.44.2@sha256:2608f0661bd4599b9c42bca8739099464455045e167078ac2b6e2644d8f357f8
            env:
              TZ: Europe/London
              DOCKER_ENABLE_SECURITY: "false"
              SECURITY_ENABLE_LOGIN: "false"
              INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "true"
            probes:
              liveness: &probe
                enabled: true
                type: HTTP
                path: /api/v1/info/status
              readiness: *probe
              startup:
                <<: *probe
                spec:
                  failureThreshold: 90
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: stirling-pdf
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames: ["pdf.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        enabled: true
        existingClaim: stirling-pdf
        globalMounts:
          - path: /configs
      logs:
        enabled: true
        type: emptyDir
      tmp:
        enabled: true
        type: emptyDir
      tessdata:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /usr/share/tessdata
