---
# yaml-language-server: $schema=https://schemas.tholinka.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - &gateway
      namespace: network
      sectionName: http
      name: internal
    - <<: *gateway
      name: external-root
    - <<: *gateway
      name: external
    - <<: *gateway
      name: external
      sectionName: ${SECRET_DOMAIN_2}-http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
