# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:XkJMnQhoWnD2jM+hC1oNrvDwICVmoN8oJp0GFAP5NWugaymDtbz5qYM57AwcXQBxvqgWtlfbWq7befRfUG9R8FRxY0vMkQ1pTzpqWJyA5Zbnpjb4vYRpJH17MvZFQEee/LElWZOLbXEYTIA1FptBxd3yjGgnWUOEiXRmP3cs+UBqmwfvBYrGUGiIn1m2tuqy9U74IIRtShFpNUCoYTiUEvE5A8m7/GKNXrb7t/d9eY2sOlRa4A==,iv:J1qfB42yZiHV4EeaIwL2UuI7SU/h5QK/4nGIjazYlZ8=,tag:vYnibfyGl/GEbRg6v5ojNA==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4qF3TWRZ7qKtoUz0ofAVvY/+a0Vs9a+Cx3/KPEG8abUvTZ+c,iv:+n4KH0+C11zZkoBaL2dicqC5/GBH01SkFN0PeB36Eh8=,tag:QpSO8a/+DM3z627FanUjhQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1t9dt4x2h77mduu8xm0ru3hyr5vy8afrw9474ukfv7ws5hae5kc8styg36m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcVZCT2hWaUd6SktUeXNi
        Vlc5ZlEyajB0T0lVYkZ6VHkrTGdUcytPSVRVCjVId1JNaWlFdjJwQkJ6d1p2MjJp
        LzdFSDlGczBJOUJraFUrYi9XdmlreDQKLS0tIDF4cFpZU0YxbTRsNGltL0ppSzF2
        SnRWT3F5L1g3MDdDOE9HK1cvK1BHM1UK68nDambCJtuhqDJTqKEPS2yP2SxhJgDx
        ePbGnrFnjB7tIpiHchImvEOzUEjds3ag31aKmKXbvy1gx78gsbbWbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-21T13:28:52Z"
  mac: ENC[AES256_GCM,data:2814X/ZgIaSBRV1NcN0JvJTwgKLDdXdWx6I9q5/1zq4JXCah8ve70XcyL9xLEbdpuEaCYxGPYhce3UgKuBPKzIkz/bYPFmXyG+SYYfecAmJHrjpNe8fB0Mr2boJFCedrxe/dWdQ56C3byFlHqy539ei3v1GlybUKih2mYK5wjBc=,iv:Z7JXaG+DqpDGMOFjRtGFQ6RL5n753p8w7IS0ey1x6yM=,tag:+BTjF4/5eHlq1AsB67f4YQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
