---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nut-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      nut-exporter:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              NUT_EXPORTER_SERVER: aionios.internal
              NUT_EXPORTER_SERVERPORT: 3493
            envFrom:
              - secretRef:
                  name: nut-exporter-secret
            args:
              # the first time I set this, the first and last entries were ignored, so I have doubled them.
              - --nut.vars_enable="battery.charge,battery.charge,battery.runtime,battery.voltage,battery.voltage.nominal,input.voltage,input.voltage.nominal,output.voltage,output.voltage.nominal,ups.realpower,ups.load,ups.status,ups.status"
            image:
              repository: ghcr.io/druggeri/nut_exporter
              tag: 3.2.0
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              limits: &resources
                memory: 100Mi
              requests:
                <<: *resources
                cpu: 10m
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: nut-exporter
    service:
      app:
        ports:
          http:
            port: 9199
    serviceMonitor:
      app:
        endpoints:
          - port: http
            scheme: http
            path: /ups_metrics
            interval: 1m
            scrapeTimeout: 10s
