# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
components:
  - ../../components/common
resources:
  - ./paperless/ks.yaml
  - ./it-tools/ks.yaml
  - ./home-assistant/ks.yaml
  - ./open-webui/ks.yaml
  - ./stirling-pdf/ks.yaml
