---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: download
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./slskd/ks.yaml
  - ./calibre-downloader/ks.yaml
  - ./notifier/ks.yaml
  - ./nzbget/ks.yaml
