---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: download
components:
  - ../../components/common
resources:
  - ./sabnzbd/ks.yaml
  - ./slskd/ks.yaml
  - ./calibre-downloader/ks.yaml
  - ./webhook/ks.yaml
