---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app synapse
  namespace: &namespace communication
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
    - ../../../../components/gatus/external
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/communication/matrix-synapse/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 20Gi
      VOLSYNC_CACHE_CAPACITY: 4Gi
      GATUS_SUBDOMAIN: synapse
      GATUS_PATH: /_matrix/client/versions
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
