---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: grafana
spec:
  image: docker.io/grafana/mcp-grafana:1.1.0@sha256:f21a19cebbfa7c3a76ef1746171e5ffc3601064e432f593e7c6cb526e5216e5f
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 8000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.observability.svc.cluster.local:3000
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          args:
            - -t
            - streamable-http
            - --address
            - 0.0.0.0:8000
            - --allowed-hosts
            - "*"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
  groupRef:
    name: mcp-tools
