---
directories:
  downloads: /media/Downloads/soulseek/complete
  incomplete: /media/Downloads/soulseek/incomplete
flags:
  no_version_check: true
metrics:
  enabled: true
  url: /metrics
  authentication:
    disabled: true
remote_configuration: false
shares:
  directories:
    - /media/Downloads/soulseek/shared
  filters:
    - \.ini$
    - Thumbs.db$
    - \.DS_Store$
transfers:
  download:
    destination:
      permissions:
        mode: 750
    retry:
      partial: resume
      attempts: 3
      delay: 5000
      max_delay: 60000
