---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      home-assistant:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.8.0@sha256:f418461e9481e7ad27a0d01ba201b810ce1a7f117ae3fe78d0529db4f15c244f
            env:
              HOME_ASSISTANT_EXTERNAL_URL: hass.${SECRET_DOMAIN}
              HOME_ASSISTANT_PURGE_KEEP_DAYS: 30
              TZ: Europe/London
              HASS_HTTP_TRUSTED_PROXY_1: 10.69.0.0/16
              HASS_HTTP_TRUSTED_PROXY_2: 10.0.20.0/24
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "multus-iot",
            "namespace": "network",
            "ips": ["10.0.40.241/24"],
            "mac": "48:c3:71:7c:c5:27"
          }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: *app
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /config/.venv
                subPath: .venv
              - path: /config/logs
                subPath: logs
              - path: /config/tts
                subPath: tts
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - hass.${SECRET_DOMAIN}
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
    service:
      app:
        ports:
          http:
            port: 8123
