---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: owncast
spec:
  chartRef:
    kind: OCIRepository
    name: owncast
  interval: 1h
  values:
    controllers:
      owncast:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [44, 10000]
            seccompProfile: { type: RuntimeDefault }
        containers:
          app:
            image:
              repository: ghcr.io/phycoforce/owncast
              tag: 0.2.5@sha256:7e2bb800bae114f408379f07d2e309f3cebda533fe22fcff8b54406db2723e13
            env:
              TZ: Europe/London
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
                #memory: 250Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: owncast-gpu
    service:
      app:
        ports:
          http:
            port: *port
      rtmp:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.0.20.244
          external-dns.alpha.kubernetes.io/hostname: stream-ingest.${SECRET_DOMAIN_2}
        ports:
          rtmp:
            enabled: true
            port: 1935
            protocol: TCP
    route:
      app:
        hostnames: ["stream.${SECRET_DOMAIN_2}"]
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      tmp:
        type: emptyDir
        globalMounts:
          - path: /config/data/logs
