# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:c1QPR6E9ZO1CKe67Hug7qGl/EZtPe43zW2BqZfvHPwXCrFODPc/PjA==,iv:zqEmtRz/ufPPQlwFg+ZsDb/uTX/4EJ5VBpzLmGIgbtk=,tag:rEKvSM/J8RV4gaA6vJCkpw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1t9dt4x2h77mduu8xm0ru3hyr5vy8afrw9474ukfv7ws5hae5kc8styg36m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud0ptbDIvSlJwZDBlaG91
        OEUrdEFXWDJ1QjRDbEVISm1nT1UzeXdPNWx3CmJST0ZiTHFjYVUzOWY0dDlNYXZK
        NmJBNUZ5MkpHbXJtU2xRd0hOOVpZaGsKLS0tIFV6OEtVN3ZXZHVHbjJWaDkzY0I0
        cW1qNzc3ZHBSZXIvUVpiU3NGcVpTTjgK7nM+q7HSyyVNA2I35fMdym4gusjSpvet
        mZxvrYrY0+jUETFHeRrCiQ4B4iGGI0cC021yP9kRzgovI/qtyi/cdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-14T12:33:52Z"
  mac: ENC[AES256_GCM,data:s85r/wrQmAzoR171bGeuuvO/Fx74+U3QXECWhI5M+tbl38pEu88GKtk9GS6I/WrpKIy4VAvLuVawbhoLAsZDPjJnSXyfDHmqbYbaoB3vF8vjGpXpP82lmCK2+c9qXbJoq9CAp6TY9HlO1zOhBzXrdBPq+vhN1wIn3PFbnBpvlV4=,iv:Rlq4LycWYZLgFDAt0CYqQBwyrtexWW1y/Aq/SjTuE1U=,tag:S5SP1Ct+K1Rdjn3lgFFuqw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
