---
log:
  level: info

authentication_backend:
  ldap:
    address: ldap://lldap.security.svc.cluster.local:389
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: dc=home,dc=arpa
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    user: uid=admin,ou=people,dc=home,dc=arpa
    attributes:
      username: uid
      display_name: displayName
      group_name: cn
      mail: mail
      member_of: memberOf
  password_reset:
    disable: true
  refresh_interval: 1m

regulation:
  max_retries: 3
  find_time: 1h
  ban_time: 1d

session:
  name: authelia-home-ops
  inactivity: 3d
  expiration: 7d
  remember_me: 6M
  cookies:
    - domain: {{ env "SECRET_DOMAIN" }}
      authelia_url: https://auth.{{ env "SECRET_DOMAIN" }}
  redis:
    database_index: 2
    host: dragonfly.database.svc.cluster.local

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
  rules: []

notifier:
  disable_startup_check: false
  smtp:
    address: 'smtp.gmail.com:587'
    timeout: '5s'
    username: '{{ env "SECRET_SMTP_USERNAME" }}'
    password: '{{ env "SECRET_SMTP_PASSWORD" }}'
    sender: '{{ env "SECRET_AUTHELIA_SMTP_ADDRESS" }}'
    identifier: 'localhost'
    subject: "[Authelia] {title}"
    startup_check_address: '{{ env "SECRET_AUTHELIA_SMTP_STARTUP_ADDRESS" }}'
    disable_require_tls: false
    disable_starttls: false
    disable_html_emails: false

identity_validation:
  reset_password:
    jwt_secret: '{{ env "JWT_SECRET" }}'

identity_providers:
  oidc:
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins_from_client_redirect_uris: true
    jwks:
      - key_id: default
        key: {{ env "JWKS_KEY" | b64dec | mindent 10 "|" | msquote }}
    clients:
      - client_id: grafana
        client_name: Grafana
        client_secret: '{{ env "GRAFANA_OAUTH_CLIENT_SECRET" }}'
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - https://grafana.{{ env "SECRET_DOMAIN" }}/login/generic_oauth
        userinfo_signed_response_alg: none
