---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudflared
  namespace: &namespace network
spec:
  dependsOn:
    - name: external-secrets
      namespace: security
  interval: 1h
  path: ./kubernetes/apps/network/cloudflared/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - kind: Secret
        name: cloudflare-tunnel-id-secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
