---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  copyMethod: Snapshot
  credentialProjection:
    enabled: true
  repository:
    kind: ClusterRepository
    name: nas
  retention:
    keepHourly: 24
    keepDaily: 7
  sources:
    - pvc:
        name: ${APP}
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
