---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  copyMethod: Snapshot
  credentialProjection:
    enabled: true
  repository:
    kind: ClusterRepository
    name: nas
  retention:
    keepHourly: 24
    keepDaily: 7
  sources:
    - pvc:
        name: ${APP}
  verification:
    deep:
      schedule:
        cron: H 5 1 * *
        timezone: Europe/London
    quick:
      cron: H 3 * * *
      timezone: Europe/London
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
