---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  compression:
    compressor: zstd
  credentialProjection:
    enabled: true
  mover:
    cache:
      capacity: ${KOPIUR_CAPACITY:=5Gi}
      mode: Persistent
      storageClassName: miroir-replicated
    podSecurityContext:
      fsGroup: 1001
      fsGroupChangePolicy: OnRootMismatch
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
    ttlSecondsAfterFinished: 300
  repository:
    kind: ClusterRepository
    name: nas
  retention:
    keepLatest: 3
    keepHourly: 24
    keepDaily: 7
    keepWeekly: 4
  sources:
    - pvc:
        name: ${APP}
  verification:
    deep:
      schedule:
        cron: H 5 1 * *
    quick:
      schedule:
        cron: H 3 * * *
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
