---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: palworld-dashboard-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: palworld-dashboard-secret
    template:
      engineVersion: v2
      data:
        PANEL_INITIAL_ADMIN_PASSWORD: "{{ .PANEL_PASSWORD }}"
        PALWORLD_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: palworld
