---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resourceclaimtemplate.yaml
  - ./gemma4-e4b
  - ./gemma3-4b
  - ./llava-llama3
  - ./qwen3.5-9b
