---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mihomo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mihomo-secret
    template:
      engineVersion: v2
      data:
        VPS_IP: "{{ .VPS_IP }}"
        SS_PSK: "{{ .SS_PSK }}"
  dataFrom:
    - extract:
        key: mihomo
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mihomo-sites
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mihomo-secret-sites
    template:
      engineVersion: v2
      data:
        secret-sites.yaml: |
          payload:
          {{- range regexSplit "\\s+" (.DOMAINS | trim) -1 }}
            - '+.{{ . | trimAll "." }}'
          {{- end }}
  dataFrom:
    - extract:
        key: mihomo
