---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      ollama:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: intelanalytics/ipex-llm-inference-cpp-xpu
              # repository: ghcr.io/joryirving/ollama-intel-gpu
              tag: 2.3.0-SNAPSHOT
              # tag: ipex-llm-v.0.0.1-2
            command:
              - /bin/sh
              - -c
              - mkdir -p /llm/ollama && cd /llm/ollama && init-ollama && exec ./ollama serve
            securityContext:
              privileged: true
            env:
              TZ: Europe/London
              OLLAMA_MODELS: &modelPath /models
              # ONEAPI_DEVICE_SELECTOR: level_zero:0
              # IPEX_LLM_NUM_CTX: 16384
              no_proxy: localhost,127.0.0.1
              OLLAMA_HOST: 0.0.0.0
              DEVICE: Arc
              OLLAMA_INTEL_GPU: true
              OLLAMA_NUM_GPU: 999
              ZES_ENABLE_SYSMAN: 1
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 200m
                memory: 8Gi
              limits:
                memory: 16Gi
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: ollama-gpu
    service:
      app:
        ports:
          http:
            port: &port 11434
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      ollama:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: *modelPath
            subPath: models
          - path: /root/.ollama
            subPath: config
      dev:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - readOnly: true
