---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      ollama:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: intelanalytics/ipex-llm-inference-cpp-xpu
              # repository: ghcr.io/joryirving/ollama-intel-gpu
              tag: 2.3.0-SNAPSHOT
              # tag: ipex-llm-v.0.0.1-2
            command:
              - /bin/sh
              - -c
              - mkdir -p /llm/ollama && cd /llm/ollama && init-ollama && exec ./ollama serve
            securityContext:
              privileged: true
            env:
              OLLAMA_MODELS: &modelPath /models
              # ONEAPI_DEVICE_SELECTOR: level_zero:0
              # IPEX_LLM_NUM_CTX: 16384
              no_proxy: localhost,127.0.0.1
              OLLAMA_HOST: 0.0.0.0
              DEVICE: Arc
              OLLAMA_INTEL_GPU: true
              OLLAMA_NUM_GPU: 999
              ZES_ENABLE_SYSMAN: 1
            resources:
              requests:
                cpu: 200m
                memory: 8Gi
              limits:
                memory: 16Gi
                gpu.intel.com/i915: 1
    service:
      app:
        ports:
          http:
            port: &port 11434
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
    persistence:
      models:
        type: custom
        volumeSpec:
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                storageClassName: "openebs-hostpath"
                resources:
                  requests:
                    storage: 50Gi
        advancedMounts:
          ollama:
            app:
              - path: /root/.ollama
                subPath: .ollama
              - path: *modelPath
                subPath: models
      dev:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - readOnly: true
