---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: llm
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 50Gi
