---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: palworld-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: palworld-exporter
  interval: 1h
  values:
    controllers:
      palworld-exporter:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/jimmysharp/palworld_exporter
              tag: 0.2.1@sha256:96cffeee31cd8d014a29407895ca2f3b6e406272ad786ef4aa4dbfcb30e1079f
            env:
              SCRAPE_URI: http://palworld-rest.games.svc.cluster.local:8212/v1/api/metrics
              HTTP_USER: admin
              LISTEN_ADDRESS: :18212
              HTTP_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: palworld-secret
                    key: ADMIN_PASSWORD
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              limits: &resources
                memory: 128Mi
              requests:
                <<: *resources
                cpu: 10m
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        ports:
          http:
            port: 18212
    serviceMonitor:
      app:
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
