---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      unifi:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-mgt",
                "namespace": "network",
                "ips": ["192.168.0.241/24"],
                "mac": "48:C3:71:81:39:77"
              }]
        containers:
          app:
            image:
              repository: ghcr.io/jacobalberty/unifi-docker
              tag: v9.4.19@sha256:ef032346e2ebdcadaadeb27e38be55f97e6b5ed6cea333d5d82ae9b58ae4068b
              pullPolicy: IfNotPresent
            env:
              RUNAS_UID0: "false"
              UNIFI_UID: "999"
              UNIFI_GID: "999"
              UNIFI_STDOUT: "true"
              JVM_INIT_HEAP_SIZE:
              JVM_MAX_HEAP_SIZE: 1024M
            resources:
              requests:
                memory: 2Gi
                cpu: 50m
    service:
      app:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 10.0.20.243
        ports:
          https:
            port: &port 8443
            protocol: HTTPS
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          speedtest:
            enabled: true
            port: 6789
            protocol: TCP
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "true"
          gatus.home-operations.com/endpoint: |-
            conditions: ["len([BODY]) == 0"]
            dns:
              query-name: {{ .Release.Name }}.${SECRET_DOMAIN}
              query-type: A
            url: 1.1.1.1
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
            timeouts:
              request: 0s # websocket, never time out
              backendRequest: 0s # websocket, never time out
    persistence:
      config:
        enabled: true
        existingClaim: unifi
        globalMounts:
          - path: /unifi
      cert:
        type: secret
        name: '${SECRET_DOMAIN/./-}-unifi'
        advancedMounts:
          unifi:
            app:
              - path: /unifi/cert/cert.pem
                subPath: tls.crt
                readOnly: true
              - path: /unifi/cert/privkey.pem
                subPath: tls.key
                readOnly: true
              - path: /unifi/data/keystore
                subPath: keystore.jks
                readOnly: false
