---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mihomo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mihomo-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          mixed-port: 3128
          allow-lan: true
          bind-address: "*"
          mode: rule
          log-level: error
          ipv6: false
          external-controller: 127.0.0.1:9090
          geo-auto-update: false

          proxies:
            - name: vps
              type: ss
              server: "{{ .VPS_IP }}"
              port: 3128
              cipher: 2022-blake3-aes-256-gcm
              password: "{{ .SS_PSK }}"
              udp: true

          proxy-groups:
            - name: SECRET
              type: fallback
              proxies:
                - vps
                - DIRECT
              url: "http://www.gstatic.com/generate_204"
              interval: 30
              timeout: 5000
              max-failed-times: 3
              lazy: false

          rule-providers:
            secret-sites:
              type: inline
              behavior: domain
              payload:
              {{- range regexSplit "\\s+" (.DOMAINS | trim) -1 }}
                - '+.{{ . | trimAll "." }}'
              {{- end }}

          rules:
            - RULE-SET,secret-sites,SECRET
            - MATCH,DIRECT
  dataFrom:
    - extract:
        key: mihomo
