---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: conduwuit
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      conduwuit:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
                repository: ghcr.io/girlbossceo/conduwuit
                tag: main-00f7745ec4ebcea5f892376c5de5db1299f71696-debug
            env:
              - name: CONDUWUIT_SERVER_NAME
                value: ${SECRET_DOMAIN}
              - name: TOKIO_WORKER_THREADS
                value: "5"
              - name: CONDUWUIT_ROCKSDB_PARALLELISM_THREADS
                value: "4"
              - name: CONDUWUIT_DATABASE_PATH
                value: "/data/db"
              - name: CONDUWUIT_DATABASE_BACKEND
                value: "rocksdb"
              - name: CONDUWUIT_ADDRESS
                value: "0.0.0.0"
              - name: CONDUWUIT_PORT
                value: "8080"
              - name: RUST_LOG
                value: "info"
              - name: CONDUWUIT_ALLOW_FEDERATION
                value: "true"
              - name: CONDUWUIT_ALLOW_REGISTRATION
                value: "true"
              - name: CONDUWUIT_TRUSTED_SERVERS
                value: '["matrix.org"]'
              - name: CONDUWUIT_WELL_KNOWN__CLIENT
                value: https://matrix.${SECRET_DOMAIN}
              - name: CONDUWUIT_WELL_KNOWN__SERVER
                value: "matrix.${SECRET_DOMAIN}:443"
              - name: CONDUWUIT_MAX_REQUEST_SIZE
                value: "104857600"
#              - name: CONDUWUIT_QUERY_OVER_TCP_ONLY
#                value: "true"
              - name: CONDUWUIT_IP_LOOKUP_STRATEGY
                value: "5"
            envFrom:
              - secretRef:
                  name: conduwuit-secret
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 1Gi
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /_matrix/federation/v1/version
                    port: http
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

    service:
      main:
        controller: conduwuit
        ports:
          http:
            port: 80
            protocol: TCP
            targetPort: 8080
    ingress:
      main:
        className: external
        hosts:
          - host: ${SECRET_DOMAIN}
            paths:
              - path: /.well-known/matrix
                pathType: Prefix
                service:
                  identifier: main
                  port: 8080

          - host: matrix.${SECRET_DOMAIN}
            paths:
              - path: /_matrix
                pathType: Prefix
                service:
                  identifier: main
                  port: 8080

      int:
        className: internal
        hosts:
          - host: ${SECRET_DOMAIN}
            paths:
              - path: /.well-known/matrix
                pathType: Prefix
                service:
                  identifier: main
                  port: 8080

          - host: matrix.${SECRET_DOMAIN}
            paths:
              - path: /_matrix
                pathType: Prefix
                service:
                  identifier: main
                  port: 8080
              - path: /_conduwuit/
                pathType: Prefix
                service:
                  identifier: main
                  port: 8080
    persistence:
      data:
        existingClaim: conduwuit
        advancedMounts:
          conduwuit:
            app:
              - path: /data
