apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:JfG1py7C+uTXy/0=,iv:A8tnbhENXMq93pXM9iDmtzVN4xkz1yoXMQJ/sytX5P4=,tag:p6RZaLBQFcNXNB3S3Vo/VA==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:EjmPEpoabbkdhO6HC0uNBgOD3jkdR9ZqwdGe4InnXyxg4MSj,iv:4djA2Tefb/lpRQQsGc9xDNvHJS9lgPJgL4dgBjjCRbI=,tag:AdaVwhoXJEU4IIknZtap+w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1t9dt4x2h77mduu8xm0ru3hyr5vy8afrw9474ukfv7ws5hae5kc8styg36m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY0xReEJ4MjNrQ1FVVG5S
        SUMyU1BENEN3cTFDSG9hTWJLMnQvMVZwUEVZCkp0UUgxQmpTbW0vMkJmdE5nUFRq
        cVBHc0hyWE5xdzdGbjl6TzhBYjhNVEkKLS0tIHpzbWtFNEZGWUk4OE9PNjdra00w
        Z2pVam1yT2pBM2dTTVlkRE52UWJwSGsKL1wSN3JAgdzx8N6S7XMkCr1Z45MQ+ApH
        JaskLPU5BAXSzzLmvVN6+TC1j8xVZs4C4JUw1AeyWPYMao5BadUVtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-21T17:47:25Z"
  mac: ENC[AES256_GCM,data:lzXQXv7QTLXTwRIZHHbx7BSPyfJmfeHaZ3M8/I4aqR6AWkRAICNavLyV9quHVZ/yzFTALb3pzX3lTL8obOzcw3xBXbi2TpJYSozErRaA1R+TTVN7DV39T9UH8vAL1Sokwgp1qe48KfCXenujCVnx4IF+OznrDcMDUfFzWVbXGqQ=,iv:kxTKhM35t9g3eVMwYatIhoS85yPgAhCqu4qCdYY4vsU=,tag:8U7ap4uh3VlUHi/NRWCY7w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
