---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      open-webui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: 0.6.21@sha256:173f29b0ec706547904b25cc91c713c9bddb42262a8f454a95c61d152e474ce5
            env:
              TZ: "Europe/London"
              OLLAMA_BASE_URL: http://aionios.internal:11434
              ENABLE_RAG_WEB_SEARCH: true
              ENABLE_SEARCH_QUERY: true
              RAG_WEB_SEARCH_ENGINE: searxng
              SEARXNG_QUERY_URL: http://searxng:8080/search?q=<query>
              ENABLE_WEBSOCKET_SUPPORT: "true"
              WEBSOCKET_MANAGER: "redis"
              WEBSOCKET_REDIS_URL: redis://dragonfly.database.svc.cluster.local:6379/5
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    service:
      app:
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames: ["llm.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
    persistence:
      config:
        enabled: true
        existingClaim: open-webui
        globalMounts:
          - path: /app/backend/data
