---
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-configmap
data:
  config.yaml: |
    model_list:
      - model_name: gemma4_e4b
        litellm_params:
          model: openai/gemma4_e4b
          api_base: http://llama-gemma4-e4b.llm.svc.cluster.local:8080/v1
          api_key: llama-gemma4-e4b

      - model_name: gemma3_4b
        litellm_params:
          model: openai/gemma3_4b
          api_base: http://llama-gemma3-4b.llm.svc.cluster.local:8080/v1
          api_key: llama-gemma3-4b

      - model_name: llava_llama3
        litellm_params:
          model: openai/llava_llama3
          api_base: http://llama-llava-llama3.llm.svc.cluster.local:8080/v1
          api_key: llama-llava-llama3

    general_settings:
      health_check_endpoint: /v1/health

    router_settings:
      routing_strategy: simple-shuffle
      redis_host: os.environ/REDIS_HOST
      redis_port: os.environ/REDIS_PORT

    litellm_settings:
      success_callback: ["prometheus"]
      prometheus_adapter: true
      cache: true
      cache_params:
        type: redis
        host: os.environ/REDIS_HOST
        port: os.environ/REDIS_PORT
        namespace: litellm
        db: 6
      drop_params: true
      set_verbose: false

    environment:
      - REDIS_HOST
      - REDIS_PORT
