---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: privatebin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      privatebin:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/privatebin/nginx-fpm-alpine
              tag: 2.0.0-alpine3.22@sha256:67684f8b14430b59c493c4cc52ec3ccc378878108589ee4a9e860e7072da278d
            env:
              TZ: Europe/London
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    service:
      app:
        ports:
          http:
            port: 8080
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /srv/data
            readOnly: false
          - path: /run
            readOnly: false
          - path: /tmp
            readOnly: false
          - path: /var/lib/nginx/tmp
            readOnly: false
    route:
      app:
        hostnames: ["paste.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
