---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: squid
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      squid:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/ubuntu/squid
              tag: 6.10-24.10_beta@sha256:c9f5212b147a766529c7b026e2bebed37b998d33d0066b658596af5eba7cc65c
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44, 10000]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.0.20.242
        ports:
          http:
            port: 3128
    persistence:
      data:
        existingClaim: squid
        globalMounts:
          - path: /var/spool/squid
      config-file:
        type: configMap
        name: squid-configmap
        globalMounts:
          - path: /etc/squid/squid.conf
            subPath: squid.conf
            readOnly: true
      logs:
        type: emptyDir
        globalMounts:
          - path: /var/log/squid
      run-dir:
        type: emptyDir
        globalMounts:
          - path: /var/run
