---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: squid
  namespace: network
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 10Gi
