---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: rook-ceph
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.17.1
  url: oci://ghcr.io/rook/rook-ceph
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 1h
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    csi:
      cephFSKernelMountOptions: ms_mode=prefer-crc
      # NOTE: Enable the driver and shapshotter if you want to use CephFS
      enableCephfsDriver: false
      enableCephfsSnapshotter: false
      enableLiveness: true
      serviceMonitor:
        enabled: true
      csiRBDProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 200m
        - name : csi-resizer
          resource:
            requests:
              memory: 128Mi
              cpu: 5m
            limits:
              memory: 256Mi
              cpu: 200m
        - name : csi-attacher
          resource:
            requests:
              memory: 128Mi
              cpu: 20m
            limits:
              memory: 256Mi
              cpu: 200m
        - name : csi-snapshotter
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 200m
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 512Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
        - name : csi-omap-generator
          resource:
            requests:
              memory: 512Mi
              cpu: 25m
            limits:
              memory: 1Gi
              cpu: 500m
        - name : liveness-prometheus
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 100m

      # -- CEPH CSI RBD plugin resource requirement list
      # @default -- see values.yaml
      csiRBDPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 128Mi
              cpu: 25m
            limits:
              memory: 256Mi
              cpu: 100m
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 512Mi
              cpu: 50m
            limits:
              memory: 1Gi
              cpu: 500m
        - name : liveness-prometheus
          resource:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 100m
    image:
      repository: ghcr.io/rook/ceph
    monitoring:
      enabled: true
    resources:
      requests:
        memory: 128Mi # unchangable
        cpu: 100m # unchangable
      limits: {}
