apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:xOcXiBCMjvE9jd98a8isSSes6mdpmGJFJD9PMZiKcR6jESXkZzCEimsuseMhmZqQSnCJzqRuh/KVXtwHlPw=,iv:sdPyBV6MSCGCZvWrjbyihHdqx/BY7CQKpeALLDE8O6U=,tag:b2fA7zX6jO2ETsocFwcDsw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1t9dt4x2h77mduu8xm0ru3hyr5vy8afrw9474ukfv7ws5hae5kc8styg36m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUkFJcXo5VlpEanBJaUl5
        NDJrRFY1LzNlbVdyNmU2d2oxeUhvWnJzT25jCnVKOTF1ZmU4UTJyamdLQm9LUklN
        OStDT2ROK2pCd2N2TVF4K1MyTVJvNzAKLS0tIDljNDV1NWtQTUw3NlVLZ1JLUkpX
        QmFuT1hjcUV4eGhDWnM2bzNuQmcyTlEKw0o2yivmLdhCsc6V8/uy9EbeEokED8Mk
        Bzr65QIExx+RFJ93FC3E0YeyxkzS4t5LeQpwNJYT4ZBQglSAn0AKvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T12:49:23Z"
  mac: ENC[AES256_GCM,data:9M27AhGs3McVlTnFOiyOfyFLlOIy2GN2K4eDGan+CnF3f848u/xOQuCVHuIp5e2Bktz6GdjO22TCT+9MFAJGdUSSJq1TZY0sGv6O4fjMJ1ID5IlCyr4O0j7wlm/IldZ4hB2FTKqTd5X366FI/lGJ9Tr31zya+umVRNrpjGnQCEo=,iv:gblm5ubh93nAyPOriUYi6bV44v193KjqB9F9sB7YRR0=,tag:zbznLKPmh6hwecm66/7RGA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
