---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: fluent-bit
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.53.0
  url: oci://ghcr.io/home-operations/charts-mirror/fluent-bit
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: fluent-bit
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    config:
      service: |-
        [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level {{ .Values.logLevel }}
          Parsers_File /fluent-bit/etc/parsers.conf
          Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On
      inputs: |-
        [INPUT]
          name tail
          alias kubernetes
          path /var/log/containers/*.log
          parser containerd
          tag kubernetes.*
      filters: |-
        [FILTER]
          name kubernetes
          alias kubernetes
          match kubernetes.*
          buffer_size 0
          merge_log on
          kube_tag_prefix kubernetes.var.log.containers.
          k8s-logging.parser on
          k8s-logging.exclude on
          namespace_labels off
          annotations on
        [FILTER]
          name modify
          match kubernetes.*
          add source home-ops
        [FILTER]
          name nest
          match kubernetes.*
          wildcard pod_name
          operation lift
          nested_under kubernetes
          add_prefix k_
        [FILTER]
          name nest
          match kubernetes.*
          operation lift
          nested_under k_labels
          add_prefix k_labels_
        [FILTER]
          name modify
          match kubernetes.*
          rename k_labels_app.kubernetes.io/instance app
          rename k_labels_app.kubernetes.io/name app
          rename k_labels_app app
          rename k_labels_k8s-app app
          rename k_container_name app
      outputs: |-
        [OUTPUT]
          Name loki
          Match kubernetes.*
          host loki-headless.observability.svc.cluster.local
          port 3100
          line_format json
          labels job=fluent-bit, source=$source, namespace=$kubernetes_namespace_name
