---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: snapshot-controller
      namespace: volsync-system
  values:
      image:
        repository: harbor.icylair.com/library/volsync_1504
        tag: v0.0.2
      manageCRDs: true
      metrics:
        disableAuth: true
      replicaCount: 1
      restic:
        repository: harbor.icylair.com/library/volsync_1504
        tag: v0.0.2
      serviceAccount:
        create: true
