---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate
spec:
  chartRef:
    kind: OCIRepository
    name: teslamate
  interval: 1h
  values:
    controllers:
      teslamate:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.6@sha256:b6d3af974df781c673d37e49bdddfa14a6f5be28b18d2cb7713f0449bea4057b
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: teslamate-secret
        containers:
          app:
            image:
              repository: teslamate/teslamate
              tag: 4.1.1@sha256:cc87082e7d67a91aa11ca0fb30c2e730bc2a1fccbec9578bb3f3c64f586410f1
            env:
              TZ: Europe/London
              DISABLE_MQTT: "true"
            envFrom:
              - secretRef:
                  name: teslamate-secret
    service:
      app:
        ports:
          http:
            port: &port 4000
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
