---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: localai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: localai-secret
    template:
      engineVersion: v2
      data:
        LOCALAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        HF_TOKEN: "{{ .HF_TOKEN }}"
  dataFrom:
    - extract:
        key: localai
