---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: localai
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      localai:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/go-skynet/local-ai
              tag: v4.3.1-gpu-intel@sha256:436d005a52f043e3766c0d1311ed1bb17d28ea494ea0081b8dcf01d8600fd746
            env:
              TZ: Europe/London
              DEBUG: "false"
              LOCALAI_FORCE_META_BACKEND_CAPABILITY: intel
              LOCALAI_BACKEND_GALLERIES: >-
                [{"name":"localai","url":"https://raw.githubusercontent.com/mudler/LocalAI/master/backend/index.yaml"}]
              LOCALAI_EXTERNAL_BACKENDS: llama-cpp
              LOCALAI_MAX_ACTIVE_BACKENDS: "3"
              LOCALAI_WATCHDOG_IDLE: "true"
              LOCALAI_WATCHDOG_IDLE_TIMEOUT: "15m"
              ZES_ENABLE_SYSMAN: "1"
              MODELS_PATH: &modelPath /models
              THREADS: "6"
            envFrom: &envFrom
              - secretRef:
                  name: localai-secret
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 500m
                memory: 8Gi
              limits:
                memory: 16Gi
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: localai-gpu
    service:
      app:
        ports:
          http:
            port: 8080
    persistence:
      models:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: *modelPath
      dev:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
            readOnly: true
