---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: squid
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: squid-secret
    template:
      engineVersion: v2
      data:
        VPS_IP: "{{ .VPS_IP }}"
        DOMAINS: "{{ .DOMAINS }}"
        VPS_PASSWORD: "{{ .VPS_PASSWORD}}"
  dataFrom:
    - extract:
        key: squid
