---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
    - ../../../../components/gatus/external
    - ../../../../components/keda/nfs-scaler
  dependsOn:
    - name: keda
      namespace: observability
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: intel-device-plugin-operator
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/media/plex/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 15Gi
      VOLSYNC_CACHE_CAPACITY: 10Gi
      GATUS_PATH: /web/index.html
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
