---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./cloudflared/ks.yaml
  - ./echo-server/ks.yaml
  - ./external-dns/ks.yaml
  - ./multus/ks.yaml
  - ./unifi/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./squid/ks.yaml
  - ./certificates/ks.yaml
